image: node:10.16.3

cache:
    paths:
        - node_modules/

stages:
    - test
    - deploy

before_script:
    - npm install

test:
    stage: test
    script:
        - npm run lint
    only:
        - master
        - staging
        - dev

deploy:
    stage: deploy
    script:
        - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )"
        - "which rsync || ( apt-get update -y && apt-get install rsync -y )"
        - eval $(ssh-agent -s)

        # Inject the remote's private key
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh

        # Append keyscan output into known hosts
        - ssh-keyscan $SERVER_DOMAIN >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
        - rsync -avuz $CI_PROJECT_DIR/* $SERVER_USER@$SERVER_DOMAIN:~/$PROJECT_NAME
    only:
        # Trigger deployments only from master branch
        - master
        - staging
